name: Upload Python Package

on:
  push:
    tags:
      - 'v*'
      - 'draft/v*'

  # release:
  #   types: [published]

# allows uploading a GitHub release
permissions:
  contents: read

jobs:
  # Job to get version from tag
  get-version:
    runs-on: ubuntu-latest
    outputs:
      draft: ${{ steps.get-version.outputs.draft }}
    defaults:
      run:
        working-directory: ./turbobt
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get version from tag
        id: get-version
        run: |
          if [[ ${{ github.ref }} == refs/tags/v* ]]; then
              echo "draft=false" >> "$GITHUB_OUTPUT"
          else
              echo "draft=true" >> "$GITHUB_OUTPUT"
          fi

  # Job for Python package publishing
  publish-python:
    needs: get-version
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      id-token: write  # allows publishing to PyPI
      contents: write  # allows uploading a GitHub release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.PYTHON_DEFAULT_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_DEFAULT_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.x"
          enable-cache: true

      - name: Build
        run: uv build

      - name: Publish distribution 📦 to TestPyPI
        if: ${{ needs.get-version.outputs.draft == 'true' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: compute_horde_sdk/dist/

      - name: Publish distribution 📦 to PyPI
        if: ${{ needs.get-version.outputs.draft == 'false' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: compute_horde_sdk/dist/
