name: Upload Python Package

on:
  push:
    tags:
      - 'v*'
      - 'draft/v*'

  # release:
  #   types: [published]

# allows uploading a GitHub release
permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v6

      - name: Build release distributions
        run: run build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest

    needs:
      - release-build

    environment:
      name: testpypi
      url: https://test.pypi.org/p/turbobt

    permissions:
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      # - name: Publish package distributions to TestPyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     repository-url: https://test.pypi.org/legacy/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
